name: assignment3
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  audioplayers: ^0.10.0
  flutter:
    sdk: flutter
  material:
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    -  asset/images/color_green.png
    -  asset/images/color_black.png
    -  asset/images/color_brown.png
    -  asset/images/color_dusty_yellow.png
    -  asset/images/color_gray.png
    -  asset/images/color_red.png
    -  asset/images/color_white.png
    -  asset/images/yellow.png
    -  asset/images/family_daughter.png
    -  asset/images/family_father.png
    -  asset/images/family_grandfather.png
    -  asset/images/family_grandmother.png
    -  asset/images/family_mother.png
    -  asset/images/family_older_brother.png
    -  asset/images/family_older_sister.png
    -  asset/images/family_son.png
    -  asset/images/family_younger_brother.png
    -  asset/images/family_younger_sister.png
    -  asset/images/number_eight.png
    -  asset/images/number_five.png
    -  asset/images/number_four.png
    -  asset/images/number_nine.png
    -  asset/images/number_one.png
    -  asset/images/number_seven.png
    -  asset/images/number_six.png
    -  asset/images/number_ten.png
    -  asset/images/number_three.png
    -  asset/images/number_two.png
    -  asset/sounds/black.wav
    -  asset/sounds/brown.wav
    -  asset/sounds/dusty yellow.wav
    -  asset/sounds/gray.wav
    -  asset/sounds/green.wav
    -  asset/sounds/red.wav
    -  asset/sounds/white.wav
    -  asset/sounds/yellow.wav
    -  asset/sounds/daughter.wav
    -  asset/sounds/father.wav
    -  asset/sounds/grandfather.wav
    -  asset/sounds/grandmother.wav
    -  asset/sounds/mother.wav
    -  asset/sounds/olderbrother.wav
    -  asset/sounds/oldersister.wav
    -  asset/sounds/youngerbrother.wav
    -  asset/sounds/youngersister.wav
    -  asset/sounds/number_eight_sound.mp3
    -  asset/sounds/number_five_sound.mp3
    -  asset/sounds/number_four_sound.mp3
    -  asset/sounds/number_nine_sound.mp3
    -  asset/sounds/number_one_sound.mp3
    -  asset/sounds/number_seven_sound.mp3
    -  asset/sounds/number_six_sound.mp3
    -  asset/sounds/number_ten_sound.mp3
    -  asset/sounds/number_three_sound.mp3
    -  asset/sounds/number_two_sound.mp3
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
